name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'boredtweak-bot'
      - run: git config --global user.email 'alex.elia37@gmail.com'
      - run: npm version patch -m "[version increment] %s"
      - run: git push
